/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package adriano.b.cadastrousuario.view;

import adriano.b.cadastrousuario.controller.ClienteController;
import adriano.b.cadastrousuario.model.domain.Cliente;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Administrador
 */
public class ClienteView extends javax.swing.JInternalFrame {

    private ClienteController controller;

    /**
     * Creates new form UsuarioView
     */
    public ClienteView() {
        this.controller = new ClienteController();
        initComponents();
        this.jtbLista.getColumnModel().getColumn(0).setMaxWidth(100);
        this.jtbLista.getColumnModel().getColumn(0).setMinWidth(80);
        this.jtbLista.getColumnModel().getColumn(0).setWidth(80);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jbtNovo = new javax.swing.JButton();
        jbtSalvar = new javax.swing.JButton();
        jbtCancelar = new javax.swing.JButton();
        jbtExcluir = new javax.swing.JButton();
        jbtListar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jtfCodigo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jtfNome = new javax.swing.JTextField();
        jtfCpfCnpj = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jtfLimiteDesconto = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jcbSituacao = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtbLista = new javax.swing.JTable();

        setClosable(true);
        setTitle("Cadastro de Cliente");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Controles"));

        jbtNovo.setMnemonic('N');
        jbtNovo.setText("Novo cliente");
        jbtNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtNovoActionPerformed(evt);
            }
        });

        jbtSalvar.setMnemonic('S');
        jbtSalvar.setText("Salvar");
        jbtSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtSalvarActionPerformed(evt);
            }
        });

        jbtCancelar.setMnemonic('C');
        jbtCancelar.setText("Cancelar");
        jbtCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtCancelarActionPerformed(evt);
            }
        });

        jbtExcluir.setMnemonic('x');
        jbtExcluir.setText("Excluir");
        jbtExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtExcluirActionPerformed(evt);
            }
        });

        jbtListar.setMnemonic('L');
        jbtListar.setText("Listar");
        jbtListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtListarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jbtNovo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtListar, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jbtCancelar, jbtExcluir, jbtListar, jbtNovo, jbtSalvar});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jbtNovo)
                .addComponent(jbtSalvar)
                .addComponent(jbtCancelar)
                .addComponent(jbtExcluir)
                .addComponent(jbtListar))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Campos"));

        jLabel1.setText("Código");

        jtfCodigo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtfCodigoFocusLost(evt);
            }
        });

        jLabel2.setText("Nome");

        jtfNome.setEnabled(false);

        jtfCpfCnpj.setEnabled(false);

        jLabel3.setText("CPF/CNPJ");

        jtfLimiteDesconto.setText("0");

        jLabel4.setText("Limite desconto:");

        jcbSituacao.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Inativo", "Ativo" }));

        jLabel5.setText("Situação");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5))
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtfNome)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jtfCpfCnpj, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jtfLimiteDesconto, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtfCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jcbSituacao, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jtfCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtfNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfCpfCnpj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jtfLimiteDesconto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcbSituacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jScrollPane1.setBorder(javax.swing.BorderFactory.createTitledBorder("Lista de Clientes"));

        jtbLista.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Nome"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jtbLista);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtNovoActionPerformed
        habilitarCampos();
        this.limparCampos();
        this.controller.novo();
    }//GEN-LAST:event_jbtNovoActionPerformed

    private void jbtCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtCancelarActionPerformed
        this.desabilitarCampos();
        this.limparCampos();
        this.controller.setClienteManipulada(null);
    }//GEN-LAST:event_jbtCancelarActionPerformed

    private void jbtSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtSalvarActionPerformed
        if (!(this.controller.getClienteManipulada() == null)) {
            try {
                this.validarForm();
                enviarForm();
                this.controller.salvar();
                this.limparCampos();
                this.desabilitarCampos();
                this.jbtListarActionPerformed(evt);
                JOptionPane.showMessageDialog(this, "Salvo com sucesso!!");
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Erro ao salvar!! " + e.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Não há nada para salvar!", "Alerta", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jbtSalvarActionPerformed

    private void jbtExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtExcluirActionPerformed

        if ((!(this.controller.getClienteManipulada() == null))
                && (this.controller.getClienteManipulada().getCodigo() != null)) {
            if (JOptionPane.showConfirmDialog(null,
                    "Deseja realmente remover este registro?",
                    "Excluir registro",
                    JOptionPane.YES_NO_OPTION)
                    == JOptionPane.YES_OPTION) {
                this.controller.excluir();
                this.limparCampos();
                this.desabilitarCampos();
                this.jbtListarActionPerformed(evt);
            }
        } else {
            JOptionPane.showMessageDialog(this, "não há nada para excluir!", "Alerta",
                    JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jbtExcluirActionPerformed

    private void jbtListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtListarActionPerformed

        this.controller.pesquisar();
        //Criar um Default Table Model caso este não der certo
        DefaultTableModel model = (DefaultTableModel) jtbLista.getModel();
        model.setRowCount(0);
        for (int i = 0; i < this.controller.getLista().size(); i++) {
            model.addRow(new Object[]{
                this.controller.getLista().get(i).getCodigo().toString(),
                this.controller.getLista().get(i).getNome()
            });
        }
    }//GEN-LAST:event_jbtListarActionPerformed

    private void jtfCodigoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfCodigoFocusLost

        if (!jtfCodigo.getText().equals("")) {
            try {
                int parseInt = Integer.parseInt(jtfCodigo.getText());
                this.controller.pesquisar();
                List<Cliente> lista = this.controller.getLista();
                if (lista.size() > 0) {
                    for (int i = 0; i < lista.size(); i++) {
                        if (lista.get(i).getCodigo().equals(parseInt)) {
                            this.controller.setClienteManipulada(lista.get(i));
                            this.recebeForm();
                            this.habilitarCampos();
                            break;
                        }
                    }
                } else {
                    JOptionPane.showMessageDialog(this, "Não ha nada a listar!");
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Número inválido!");
                jtfCodigo.requestFocus();
            }
        }
    }//GEN-LAST:event_jtfCodigoFocusLost

//    Fazer validações - new String(getPassword()) para senha
//    Fazer receber os dados para o form

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtCancelar;
    private javax.swing.JButton jbtExcluir;
    private javax.swing.JButton jbtListar;
    private javax.swing.JButton jbtNovo;
    private javax.swing.JButton jbtSalvar;
    private javax.swing.JComboBox<String> jcbSituacao;
    private javax.swing.JTable jtbLista;
    private javax.swing.JTextField jtfCodigo;
    private javax.swing.JTextField jtfCpfCnpj;
    private javax.swing.JTextField jtfLimiteDesconto;
    private javax.swing.JTextField jtfNome;
    // End of variables declaration//GEN-END:variables

    private void habilitarCampos() {
        jtfNome.setEnabled(true);
        jtfCpfCnpj.setEnabled(true);
        jtfLimiteDesconto.setEnabled(true);
        jcbSituacao.setEnabled(true);
        jtfCodigo.setEditable(false);
    }

    private void desabilitarCampos() {
        jtfNome.setEnabled(false);
        jtfCpfCnpj.setEnabled(false);
        jtfLimiteDesconto.setEnabled(false);
        jcbSituacao.setEnabled(false);
        jtfCodigo.setEditable(true);
    }

    private void enviarForm() {

        if (this.jtfCodigo.getText().equals("")) {
            this.controller.getClienteManipulada().setCodigo(null);
        } else {
            this.controller.getClienteManipulada()
                    .setCodigo(Integer.parseInt(this.jtfCodigo.getText()));
        }
        this.controller.getClienteManipulada()
                .setNome(this.jtfNome.getText());
        this.controller.getClienteManipulada().setCpfCnpj(this.jtfCpfCnpj.getText());
        try {
            this.controller.getClienteManipulada().setLimiteDesconto(Integer.parseInt(jtfLimiteDesconto.getText()));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "limite inválido!");
        }
        this.controller.getClienteManipulada().setSituacao(jcbSituacao.getSelectedIndex());
    }

    private void limparCampos() {
        jtfNome.setText("");
        jtfCodigo.setText("");
        jtfCpfCnpj.setText("");
        jtfLimiteDesconto.setText("0");
        jcbSituacao.setSelectedIndex(1);
    }

    private void recebeForm() {
        jtfCodigo.setText(this.controller.getClienteManipulada().getCodigo().toString());
        jtfNome.setText(this.controller.getClienteManipulada().getNome());
        jtfCpfCnpj.setText(this.controller.getClienteManipulada().getCpfCnpj());
        jtfLimiteDesconto.setText(Integer.toString(this.controller.getClienteManipulada().getLimiteDesconto()));
        jcbSituacao.setSelectedIndex(this.controller.getClienteManipulada().getSituacao());
    }

    private void validarForm() throws Exception {

        if (jtfNome.getText().equals("")) {
            throw new Exception("O campo nome não pode ser vazio!");
        }
        if (jtfCpfCnpj.getText().equals("")) {
            throw new Exception("O campo CPF/CNPJ não pode ser vazio!");
        }
        try {
            if (Integer.parseInt(jtfLimiteDesconto.getText()) < 0) {
                throw new Exception("O Limite de desconto deve ser maior ou igual a 0!");
            }
            if (Integer.parseInt(jtfLimiteDesconto.getText()) > 100) {
                throw new Exception("O Limite de desconto deve ser menor ou igual a 100!");
            }
        } catch (Exception e) {
            throw new Exception(e.getMessage());
        }
        
    }
}
