/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package adriano.b.cadastrousuario.view;

import adriano.b.cadastrousuario.controller.ProdutoController;
import adriano.b.cadastrousuario.model.domain.Produto;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Administrador
 */
public class ProdutoView extends javax.swing.JInternalFrame {
    
    private ProdutoController controller;

    /**
     * Creates new form UsuarioView
     */
    public ProdutoView() {
        this.controller = new ProdutoController();
        initComponents();
        this.jtbLista.getColumnModel().getColumn(0).setMaxWidth(100);
        this.jtbLista.getColumnModel().getColumn(0).setMinWidth(80);
        this.jtbLista.getColumnModel().getColumn(0).setWidth(80);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jbtNovo = new javax.swing.JButton();
        jbtSalvar = new javax.swing.JButton();
        jbtCancelar = new javax.swing.JButton();
        jbtExcluir = new javax.swing.JButton();
        jbtListar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jtfCodigo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jtfDescricao = new javax.swing.JTextField();
        jcbTipo = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jcbSituacao = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jtfValor = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jtfEstoque = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtbLista = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Cadastro de Produto");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Controles"));

        jbtNovo.setMnemonic('N');
        jbtNovo.setText("Novo produto");
        jbtNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtNovoActionPerformed(evt);
            }
        });

        jbtSalvar.setMnemonic('S');
        jbtSalvar.setText("Salvar");
        jbtSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtSalvarActionPerformed(evt);
            }
        });

        jbtCancelar.setMnemonic('C');
        jbtCancelar.setText("Cancelar");
        jbtCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtCancelarActionPerformed(evt);
            }
        });

        jbtExcluir.setMnemonic('x');
        jbtExcluir.setText("Excluir");
        jbtExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtExcluirActionPerformed(evt);
            }
        });

        jbtListar.setMnemonic('L');
        jbtListar.setText("Listar");
        jbtListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtListarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jbtNovo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtListar, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jbtCancelar, jbtExcluir, jbtListar, jbtNovo, jbtSalvar});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jbtNovo)
                .addComponent(jbtSalvar)
                .addComponent(jbtCancelar)
                .addComponent(jbtExcluir)
                .addComponent(jbtListar))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Campos"));

        jLabel1.setText("Código");

        jtfCodigo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtfCodigoFocusLost(evt);
            }
        });

        jLabel2.setText("Descrição");

        jtfDescricao.setEnabled(false);

        jcbTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PRODUTO ACABADO", "MATERIA PRIMA" }));

        jLabel3.setText("Tipo de produto");

        jLabel4.setText("Situação");

        jcbSituacao.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ATIVO", "INATIVO" }));

        jLabel5.setText("Valor");

        jLabel6.setText("Estoque");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5))
                .addGap(5, 5, 5)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtfDescricao)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtfCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jcbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtfValor, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel4))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jcbSituacao, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jtfEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jtfCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtfDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jcbSituacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jtfValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6)
                        .addComponent(jtfEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(43, Short.MAX_VALUE))
        );

        jScrollPane1.setBorder(javax.swing.BorderFactory.createTitledBorder("Lista de Produtos"));

        jtbLista.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Nome"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jtbLista);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtNovoActionPerformed
        habilitarCampos();
        this.limparCampos();
        this.controller.novo();
    }//GEN-LAST:event_jbtNovoActionPerformed

    private void jbtCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtCancelarActionPerformed
        this.desabilitarCampos();
        this.limparCampos();
        this.controller.setProdutoManipulado(null);
    }//GEN-LAST:event_jbtCancelarActionPerformed

    private void jbtSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtSalvarActionPerformed
        if (!(this.controller.getProdutoManipulado()== null)) {
            try {
                this.validarForm();
                enviarForm();
                this.controller.salvar();
                this.limparCampos();
                this.desabilitarCampos();
                this.jbtListarActionPerformed(evt);
                JOptionPane.showMessageDialog(this, "Salvo com sucesso!!");
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Erro ao salvar!! " + e.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Não há nada para salvar!", "Alerta", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jbtSalvarActionPerformed

    private void jbtExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtExcluirActionPerformed
           
        
        
        if (
                (!(this.controller.getProdutoManipulado()== null))
                &&
                (this.controller.getProdutoManipulado().getCodigo()!=null)
                ) {
            if (JOptionPane.showConfirmDialog(null,
                    "Deseja realmente remover este registro?",
                    "Excluir registro",
                    JOptionPane.YES_NO_OPTION)
                    == JOptionPane.YES_OPTION) {
                this.controller.excluir();
                this.limparCampos();
                this.desabilitarCampos();
                this.jbtListarActionPerformed(evt);
            }
        } else {
            JOptionPane.showMessageDialog(this, "não há nada para excluir!", "Alerta",
                    JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jbtExcluirActionPerformed

    private void jbtListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtListarActionPerformed

        
        this.controller.pesquisar();
        //Criar um Default Table Model caso este não der certo
        DefaultTableModel model = (DefaultTableModel) jtbLista.getModel();
        model.setRowCount(0);
        for (int i = 0; i < this.controller.getLista().size(); i++) {
            model.addRow(new Object[]{
                this.controller.getLista().get(i).getCodigo().toString(),
                this.controller.getLista().get(i).getDescricao()
            });
        }
    }//GEN-LAST:event_jbtListarActionPerformed

    private void jtfCodigoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfCodigoFocusLost

        if (!jtfCodigo.getText().equals("")) {
            try {
                int parseInt = Integer.parseInt(jtfCodigo.getText());
                this.controller.pesquisar();
                List<Produto> lista = this.controller.getLista();
                if (lista.size() > 0) {
                    for (int i = 0; i < lista.size(); i++) {
                        if (lista.get(i).getCodigo().equals(parseInt)) {
                            this.controller.setProdutoManipulado(lista.get(i));
                            this.recebeForm();
                            this.habilitarCampos();
                            break;
                        }
                    }
                } else {
                    JOptionPane.showMessageDialog(this, "Não ha nada a listar!");
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Número inválido!");
                jtfCodigo.requestFocus();
            }
        }
    }//GEN-LAST:event_jtfCodigoFocusLost

//    Fazer validações - new String(getPassword()) para senha
//    Fazer receber os dados para o form

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtCancelar;
    private javax.swing.JButton jbtExcluir;
    private javax.swing.JButton jbtListar;
    private javax.swing.JButton jbtNovo;
    private javax.swing.JButton jbtSalvar;
    private javax.swing.JComboBox<String> jcbSituacao;
    private javax.swing.JComboBox<String> jcbTipo;
    private javax.swing.JTable jtbLista;
    private javax.swing.JTextField jtfCodigo;
    private javax.swing.JTextField jtfDescricao;
    private javax.swing.JTextField jtfEstoque;
    private javax.swing.JTextField jtfValor;
    // End of variables declaration//GEN-END:variables

    private void desabilitarCampos() {
        jtfDescricao.setEnabled(false);
        jtfCodigo.setEditable(true);
        jtfEstoque.setEnabled(false);
        jtfValor.setEnabled(false);
        jcbTipo.setEnabled(false);
        jcbSituacao.setEnabled(false);
    }
    
    private void habilitarCampos() {
        jtfDescricao.setEnabled(true);
        jtfCodigo.setEditable(false);
        jtfEstoque.setEnabled(true);
        jtfValor.setEnabled(true);
        jcbTipo.setEnabled(true);
        jcbSituacao.setEnabled(true);
    }
    
    private void enviarForm() {
        
        if (this.jtfCodigo.getText().equals("")) {
            this.controller.getProdutoManipulado().setCodigo(null);
        } else {
            this.controller.getProdutoManipulado()
                    .setCodigo(Integer.parseInt(this.jtfCodigo.getText()));
        }
        this.controller.getProdutoManipulado()
                .setDescricao(this.jtfDescricao.getText());
        this.controller.getProdutoManipulado()
                .setEstoque(Double.parseDouble(this.jtfEstoque.getText()));
        this.controller.getProdutoManipulado()
                .setValor(Double.parseDouble(this.jtfValor.getText()));
        this.controller.getProdutoManipulado()
                .setSituacao(this.jcbSituacao.getSelectedIndex());
        this.controller.getProdutoManipulado()
                .setTipo(this.jcbTipo.getSelectedIndex());
        
    }
    
    private void limparCampos() {
        jtfDescricao.setText("");
        jtfCodigo.setText("");
        jtfEstoque.setText("0");
        jtfValor.setText("0");
        jcbSituacao.setSelectedIndex(1);
        jcbTipo.setSelectedIndex(1);
    }
    
    private void recebeForm() {
        jtfCodigo.setText(this.controller.getProdutoManipulado().getCodigo().toString());
        jtfDescricao.setText(this.controller.getProdutoManipulado().getDescricao());
        jtfEstoque.setText(Double.toString(this.controller.getProdutoManipulado().getEstoque()));
        jtfValor.setText(Double.toString(this.controller.getProdutoManipulado().getValor()));
        jcbSituacao.setSelectedIndex(this.controller.getProdutoManipulado().getSituacao());
        jcbTipo.setSelectedIndex(this.controller.getProdutoManipulado().getTipo());
    }

    private void validarForm() throws Exception {
       
       if ( jtfDescricao.getText().equals("")) {
           throw new Exception("O campo descrição não pode ser vazio!");
       }
    }
}
